# 01-NumPy program to compute the addition of two matrices

In [26]:
#addition
def get_matrix(rows, cols, matrix_name):
    matrix = np.zeros((rows, cols)) 
    print(f"Enter elements for {matrix_name} ({rows}x{cols}):")
    for i in range(rows):
        for j in range(cols):
            element = float(input(f"Enter element at position ({i+1}, {j+1}): "))
            matrix[i, j] = element
    return matrix

#main function
rows1 = int(input("Enter the number of rows for the matrice 1: "))
cols1 = int(input("Enter the number of columns for the matrice 1: "))
rows2 = int(input("Enter the number of rows for the matrice 2: "))
cols2 = int(input("Enter the number of columns for the matrice 2: "))
matrix1 = np.zeros((rows1, cols1))
matrix2 = np.zeros((rows2, cols2))
print(matrix1.shape)
print(matrix2.shape)
if matrix1.shape != matrix2.shape:
    print("Error: Matrices must have the same dimensions for addition.")
else:
    matrix1=get_matrix(rows1,cols1,"Matrix 1")
    matrix2=get_matrix(rows2,cols2,"Matrix 2")
    print(f'Addition of Matrices results to:\n{np.add(matrix1,matrix2)}')



Enter the number of rows for the matrice 1: 1
Enter the number of columns for the matrice 1: 2
Enter the number of rows for the matrice 2: 1
Enter the number of columns for the matrice 2: 2
(1, 2)
(1, 2)
Enter elements for Matrix 1 (1x2):
Enter element at position (1, 1): 1
Enter element at position (1, 2): 2
Enter elements for Matrix 2 (1x2):
Enter element at position (1, 1): 1
Enter element at position (1, 2): 2
Addition of Matrices results to:
[[2. 4.]]


# 02-NumPy program to compute the multiplication of two matrices.

In [30]:
#matrix multiplication
def get_matrix(rows, cols, matrix_name):
    matrix = np.zeros((rows, cols)) 
    print(f"Enter elements for {matrix_name} ({rows}x{cols}):")
    for i in range(rows):
        for j in range(cols):
            element = float(input(f"Enter element at position ({i+1}, {j+1}): "))
            matrix[i, j] = element
    return matrix

#main function
rows1 = int(input("Enter the number of rows for the matrice 1: "))
cols1 = int(input("Enter the number of columns for the matrice 1: "))
rows2 = int(input("Enter the number of rows for the matrice 2: "))
cols2 = int(input("Enter the number of columns for the matrice 2: "))
matrix1 = np.zeros((rows1, cols1))
matrix2 = np.zeros((rows2, cols2))
print(matrix1.shape)
print(matrix2.shape)
if cols1 != rows2:
    print("Error: Matrices must have the same dimensions for addition.")
else:
    matrix1=get_matrix(rows1,cols1,"matrix1")
    matrix2=get_matrix(rows2,cols2,"matrix2")
    print(f'Multiplication of Matrices results to:\n{np.matmul(matrix1,matrix2)}')



Enter the number of rows for the matrice 1: 3
Enter the number of columns for the matrice 1: 2
Enter the number of rows for the matrice 2: 2
Enter the number of columns for the matrice 2: 2
(3, 2)
(2, 2)
Enter elements for matrix1 (3x2):
Enter element at position (1, 1): 4
Enter element at position (1, 2): 3
Enter element at position (2, 1): 7
Enter element at position (2, 2): 2
Enter element at position (3, 1): 9
Enter element at position (3, 2): 0
Enter elements for matrix2 (2x2):
Enter element at position (1, 1): 2
Enter element at position (1, 2): 5
Enter element at position (2, 1): 1
Enter element at position (2, 2): 6
Multiplication of Matrices results to:
[[11. 38.]
 [16. 47.]
 [18. 45.]]


# 03- NumPy program to compute the Transpose of a matrix.

In [37]:
#Transpose of a matrix
def get_matrix(rows, cols, matrix_name):
    matrix = np.zeros((rows, cols)) 
    print(f"Enter elements for {matrix_name} ({rows}x{cols}):")
    for i in range(rows):
        for j in range(cols):
            element = float(input(f"Enter element at position ({i+1}, {j+1}): "))
            matrix[i, j] = element
    return matrix

#main function
rows1 = int(input("Enter the number of rows for the matrice 1: "))
cols1 = int(input("Enter the number of columns for the matrice 1: "))

matrix1=get_matrix(rows1,cols1,"Matrix 1")
print(matrix1.shape)
print(f'matrix before transpose is \n{matrix1}')
print(f'\nTranspose Matrix is :\n{np.transpose(matrix1)}') #or matrix.T



Enter the number of rows for the matrice 1: 2
Enter the number of columns for the matrice 1: 3
Enter elements for Matrix 1 (2x3):
Enter element at position (1, 1): 1
Enter element at position (1, 2): 2
Enter element at position (1, 3): 3
Enter element at position (2, 1): 4
Enter element at position (2, 2): 5
Enter element at position (2, 3): 6
(2, 3)
matrix before transpose is 
[[1. 2. 3.]
 [4. 5. 6.]]

Transpose Matrix is :
[[1. 4.]
 [2. 5.]
 [3. 6.]]


# 04-NumPy program to compute the determinant of a matrix

In [38]:
#Det of a matrix
def get_matrix(rows, cols, matrix_name):
    matrix = np.zeros((rows, cols)) 
    print(f"Enter elements for {matrix_name} ({rows}x{cols}):")
    for i in range(rows):
        for j in range(cols):
            element = float(input(f"Enter element at position ({i+1}, {j+1}): "))
            matrix[i, j] = element
    return matrix

#main function
rows1 = int(input("Enter the number of rows for the matrice 1: "))
cols1 = int(input("Enter the number of columns for the matrice 1: "))

matrix1=get_matrix(rows1,cols1,"Matrix 1")
print(matrix1.shape)
print(f'Determinant  Matrix is :\n{np.linalg.det(matrix1)}') #or matrix.T



Enter the number of rows for the matrice 1: 3
Enter the number of columns for the matrice 1: 3
Enter elements for Matrix 1 (3x3):
Enter element at position (1, 1): 1
Enter element at position (1, 2): 5
Enter element at position (1, 3): 3
Enter element at position (2, 1): 2
Enter element at position (2, 2): 4
Enter element at position (2, 3): 7
Enter element at position (3, 1): 4
Enter element at position (3, 2): 6
Enter element at position (3, 3): 2
(3, 3)
Determinant  Matrix is :
74.00000000000003


# 05-NumPy program to compute the inverse of a square matrix.

In [39]:
#INVERSE of a matrix
def get_matrix(rows, cols, matrix_name):
    matrix = np.zeros((rows, cols)) 
    print(f"Enter elements for {matrix_name} ({rows}x{cols}):")
    for i in range(rows):
        for j in range(cols):
            element = float(input(f"Enter element at position ({i+1}, {j+1}): "))
            matrix[i, j] = element
    return matrix

#main function
rows1 = int(input("Enter the number of rows for the matrice 1: "))
cols1 = int(input("Enter the number of columns for the matrice 1: "))

matrix1=get_matrix(rows1,cols1,"Matrix 1")
print(matrix1.shape)
print(f'INVERSE  Matrix is :\n{np.linalg.inv(matrix1)}') #or matrix.T



Enter the number of rows for the matrice 1: 2
Enter the number of columns for the matrice 1: 2
Enter elements for Matrix 1 (2x2):
Enter element at position (1, 1): 4
Enter element at position (1, 2): 7
Enter element at position (2, 1): 2
Enter element at position (2, 2): 6
(2, 2)
INVERSE  Matrix is :
[[ 0.6 -0.7]
 [-0.2  0.4]]


# 06- NumPy program to compute the dot product of two vectors.

In [46]:
vector_size1=int(input("Enter the size of the Vector1:"))
vector_size2=int(input("Enter the size of the Vector2:"))
v1=[]
v2=[]
if vector_size1==vector_size2:
    for i in range(vector_size1):
        l=float(input(f'Enter the element {i+1} for v1:'))
        v1.append(l)
    for i in range(vector_size2):
        l=float(input(f'Enter the element {i+1} for v2:'))
        v2.append(l)
    v1=np.array(v1)
    v2=np.array(v2)
    print(f'\nVector Dot product is :{np.dot(v1,v2)}')
else:
    print('not compatable dimension')
    

Enter the size of the Vector1:2
Enter the size of the Vector2:2
Enter the element 1 for v1:1
Enter the element 2 for v1:2
Enter the element 1 for v2:3
Enter the element 2 for v2:1

Vector Dot product is :5.0


# Thank You